# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainUI.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets, Qt

from lib_modulo import QLabelClickable


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(802, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.frame = QtWidgets.QFrame(self.centralwidget)
        self.frame.setGeometry(QtCore.QRect(10, 100, 791, 441))
        self.frame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.frame.setObjectName("frame")
        self.labelImagen = QLabelClickable(self)
        self.labelImagen.setGeometry(30, 180, 280, 310)
        self.labelImagen.setToolTip("Imagen")
        # self.labelImagen.setCursor(Qt.PointingHandCursor)

        self.labelImagen.setStyleSheet("QLabel {background-color: white; border: 1px solid "
                                       "#01DFD7; border-radius: 2px;}")

        # self.labelImagen.setAlignment(Qt.AlignCenter)
        self.layoutWidget = QtWidgets.QWidget(self.frame)
        self.layoutWidget.setGeometry(QtCore.QRect(330, 100, 443, 241))
        self.layoutWidget.setObjectName("layoutWidget")
        self.formLayout = QtWidgets.QFormLayout(self.layoutWidget)
        self.formLayout.setContentsMargins(0, 0, 0, 0)
        self.formLayout.setObjectName("formLayout")
        self.label_3 = QtWidgets.QLabel(self.layoutWidget)
        self.label_3.setObjectName("label_3")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.LabelRole, self.label_3)
        self.editNumero = QtWidgets.QLineEdit(self.layoutWidget)
        self.editNumero.setObjectName("editNumero")
        self.formLayout.setWidget(0, QtWidgets.QFormLayout.FieldRole, self.editNumero)
        self.label_4 = QtWidgets.QLabel(self.layoutWidget)
        self.label_4.setObjectName("label_4")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.LabelRole, self.label_4)
        self.editNombre = QtWidgets.QLineEdit(self.layoutWidget)
        self.editNombre.setObjectName("editNombre")
        self.formLayout.setWidget(1, QtWidgets.QFormLayout.FieldRole, self.editNombre)
        self.label_5 = QtWidgets.QLabel(self.layoutWidget)
        self.label_5.setObjectName("label_5")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.LabelRole, self.label_5)
        self.editTrarjeta = QtWidgets.QLineEdit(self.layoutWidget)
        self.editTrarjeta.setObjectName("editTrarjeta")
        self.formLayout.setWidget(2, QtWidgets.QFormLayout.FieldRole, self.editTrarjeta)
        self.label_6 = QtWidgets.QLabel(self.layoutWidget)
        self.label_6.setObjectName("label_6")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.LabelRole, self.label_6)
        self.editPuesto = QtWidgets.QLineEdit(self.layoutWidget)
        self.editPuesto.setObjectName("editPuesto")
        self.formLayout.setWidget(3, QtWidgets.QFormLayout.FieldRole, self.editPuesto)
        self.label_7 = QtWidgets.QLabel(self.layoutWidget)
        self.label_7.setObjectName("label_7")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.LabelRole, self.label_7)
        self.editEmergencia = QtWidgets.QLineEdit(self.layoutWidget)
        self.editEmergencia.setObjectName("editEmergencia")
        self.formLayout.setWidget(4, QtWidgets.QFormLayout.FieldRole, self.editEmergencia)
        self.label_8 = QtWidgets.QLabel(self.layoutWidget)
        self.label_8.setObjectName("label_8")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.LabelRole, self.label_8)
        self.textEdit = QtWidgets.QTextEdit(self.layoutWidget)
        self.textEdit.setObjectName("textEdit")
        self.formLayout.setWidget(5, QtWidgets.QFormLayout.FieldRole, self.textEdit)
        self.layoutWidget1 = QtWidgets.QWidget(self.centralwidget)
        self.layoutWidget1.setGeometry(QtCore.QRect(10, 0, 781, 91))
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.layoutWidget1)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(self.layoutWidget1)
        font = QtGui.QFont()
        font.setFamily("moonhouse")
        font.setPointSize(47)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.line_2 = QtWidgets.QFrame(self.layoutWidget1)
        self.line_2.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.horizontalLayout.addWidget(self.line_2)
        self.horizontalLayout_4.addLayout(self.horizontalLayout)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.buttonCreate = QtWidgets.QPushButton(self.layoutWidget1)
        self.buttonCreate.setObjectName("buttonCreate")
        self.horizontalLayout_2.addWidget(self.buttonCreate)
        self.buttonEdit = QtWidgets.QPushButton(self.layoutWidget1)
        self.buttonEdit.setObjectName("buttonEdit")
        self.horizontalLayout_2.addWidget(self.buttonEdit)
        self.buttonDelete = QtWidgets.QPushButton(self.layoutWidget1)
        self.buttonDelete.setObjectName("buttonDelete")
        self.horizontalLayout_2.addWidget(self.buttonDelete)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_2 = QtWidgets.QLabel(self.layoutWidget1)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_3.addWidget(self.label_2)
        self.lineSearch = QtWidgets.QLineEdit(self.layoutWidget1)
        self.lineSearch.setObjectName("lineSearch")
        self.horizontalLayout_3.addWidget(self.lineSearch)
        self.verticalLayout.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_4.addLayout(self.verticalLayout)
        self.verticalLayout_2.addLayout(self.horizontalLayout_4)
        self.line = QtWidgets.QFrame(self.layoutWidget1)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.verticalLayout_2.addWidget(self.line)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 802, 21))
        self.menubar.setObjectName("menubar")
        self.menuArchivo = QtWidgets.QMenu(self.menubar)
        self.menuArchivo.setObjectName("menuArchivo")
        self.menuArchivo_2 = QtWidgets.QMenu(self.menubar)
        self.menuArchivo_2.setObjectName("menuArchivo_2")
        self.menuAyuda = QtWidgets.QMenu(self.menubar)
        self.menuAyuda.setObjectName("menuAyuda")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.conectBBDD = QtWidgets.QAction(MainWindow)
        self.conectBBDD.setObjectName("conectBBDD")
        self.actionSalir = QtWidgets.QAction(MainWindow)
        self.actionSalir.setObjectName("actionSalir")
        self.actionBuscar = QtWidgets.QAction(MainWindow)
        self.actionBuscar.setObjectName("actionBuscar")
        self.actionCrear = QtWidgets.QAction(MainWindow)
        self.actionCrear.setObjectName("actionCrear")
        self.actionEliminar = QtWidgets.QAction(MainWindow)
        self.actionEliminar.setObjectName("actionEliminar")
        self.actionContactar_a_soporte = QtWidgets.QAction(MainWindow)
        self.actionContactar_a_soporte.setObjectName("actionContactar_a_soporte")
        self.actionLicencia = QtWidgets.QAction(MainWindow)
        self.actionLicencia.setObjectName("actionLicencia")
        self.actionEliminar_2 = QtWidgets.QAction(MainWindow)
        self.actionEliminar_2.setObjectName("actionEliminar_2")
        self.menuArchivo.addAction(self.conectBBDD)
        self.menuArchivo.addSeparator()
        self.menuArchivo.addAction(self.actionSalir)
        self.menuArchivo_2.addAction(self.actionBuscar)
        self.menuArchivo_2.addSeparator()
        self.menuArchivo_2.addAction(self.actionCrear)
        self.menuArchivo_2.addSeparator()
        self.menuArchivo_2.addAction(self.actionEliminar)
        self.menuArchivo_2.addSeparator()
        self.menuArchivo_2.addAction(self.actionEliminar_2)
        self.menuAyuda.addAction(self.actionContactar_a_soporte)
        self.menuAyuda.addSeparator()
        self.menuAyuda.addAction(self.actionLicencia)
        self.menubar.addAction(self.menuArchivo.menuAction())
        self.menubar.addAction(self.menuArchivo_2.menuAction())
        self.menubar.addAction(self.menuAyuda.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label_3.setText(_translate("MainWindow", "No. Trabajador:"))
        self.label_4.setText(_translate("MainWindow", "Nombre:"))
        self.label_5.setText(_translate("MainWindow", "Tarjeta:"))
        self.label_6.setText(_translate("MainWindow", "Cargo / Puesto"))
        self.label_7.setText(_translate("MainWindow", "Emergencia:"))
        self.label_8.setText(_translate("MainWindow", "Notas:"))
        self.label.setText(_translate("MainWindow", "Peñoles"))
        self.buttonCreate.setText(_translate("MainWindow", "Crear"))
        self.buttonEdit.setText(_translate("MainWindow", "Editar"))
        self.buttonDelete.setText(_translate("MainWindow", "Eliminar"))
        self.label_2.setText(_translate("MainWindow", "Search"))
        self.menuArchivo.setTitle(_translate("MainWindow", "App"))
        self.menuArchivo_2.setTitle(_translate("MainWindow", "Archivo"))
        self.menuAyuda.setTitle(_translate("MainWindow", "Ayuda"))
        self.conectBBDD.setText(_translate("MainWindow", "Conectar a BBDD"))
        self.actionSalir.setText(_translate("MainWindow", "Salir"))
        self.actionBuscar.setText(_translate("MainWindow", "Buscar"))
        self.actionCrear.setText(_translate("MainWindow", "Crear"))
        self.actionEliminar.setText(_translate("MainWindow", "Editar"))
        self.actionContactar_a_soporte.setText(_translate("MainWindow", "Contactar a soporte"))
        self.actionLicencia.setText(_translate("MainWindow", "Licencia"))
        self.actionEliminar_2.setText(_translate("MainWindow", "Eliminar"))


if __name__ == "__main__":
    import sys

    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
